/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voters_admin;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author tosyngy
 */
public class IssueCard extends javax.swing.JFrame {

    Variables var;
    DbConnect db;
    JOptionPane jp;
    static String permit = "";
    GregorianCalendar gc = new GregorianCalendar();
    int id;

    /**
     * Creates new form Login
     */
    public IssueCard() {
        initComponents();
        jp = new JOptionPane();
        db = new DbConnect();
        var= new Variables();
        userLogin(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("FEDERAL REPUBLIC OF NIGERIA ");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 0, 300, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("INDEPENDENT NATIONAL ELECTORAL COMMISSION");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 20, 360, 20);

        jLabel14.setFont(new java.awt.Font("Impact", 1, 11)); // NOI18N
        jLabel14.setText("VOTER REGISTRATION");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(120, 40, 120, 20);

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 60, 410, 2);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel24.setAlignmentX(0.5F);
        jLabel24.setAutoscrolls(true);
        jLabel24.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel24.setPreferredSize(new java.awt.Dimension(176, 144));
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 130, 90, 100);

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel4.setText("PU:");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(370, 60, 10, 20);

        jLabel6.setBackground(new java.awt.Color(102, 255, 102));
        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel6.setText("VIN:");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 60, 370, 20);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 7)); // NOI18N
        jLabel7.setText("DATE OF ISSUE:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 110, 230, 10);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel8.setText("OCCUPATION");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(120, 180, 90, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(120, 190, 50, 20);

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel11.setText("SURNAME, First name Other names");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(120, 120, 240, 10);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("FIRSTNAME, SECONDNAME, OTHERNAME");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(120, 130, 250, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(280, 190, 50, 20);

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel17.setText("GENDER");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(280, 180, 90, 10);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(120, 220, 250, 20);

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel19.setText("ADDRESS");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(120, 210, 90, 10);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(120, 160, 70, 20);

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel21.setText("DATE OF BIRTH");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(120, 150, 90, 10);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(280, 160, 50, 20);

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 8)); // NOI18N
        jLabel23.setText("AGE");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(280, 150, 90, 10);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 40, 380, 240);

        jButton1.setText("Issue and Print Card  ");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 300, 160, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 300, 130, 23);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 2, 13)); // NOI18N
        jLabel5.setText("Powered by Groupname");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 330, 150, 20);

        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 30, 400, 260);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Issue Card"));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 440, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
           
                db.ps = db.con.prepareStatement("UPDATE `register_detaila` SET  `colectiondate`=?,collectiontime=?,issue_agent=?,status=? where id=?");
                Date d = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                db.ps.setString(1, dateFormat.format(d.getTime()));
                db.ps.setString(2, timeFormat.format(d.getTime()));
                db.ps.setString(3, var.getUsername());//place of isseue
                db.ps.setString(4, "1");
                db.ps.setInt(5, id);
                db.ps.executeUpdate();
                log("issue card to " + var.getAgentId());
                JOptionPane.showMessageDialog(rootPane, "Card Issue Updated Successful!!!");
                jTextArea1.print();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "There was Issue while confirming password");
        }
        //        userLogin();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueCard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    void userLogin(int i) {
 
        //testing if internet connection is available

        try {
            String sqlQuery = "";
//            if (i == 0) {
//                sqlQuery = "select *  from register_detaila where reg_id='" + var.getAgentId() + "'";
//            } else {
                sqlQuery = "select *  from register_detaila where reg_id='" + var.getAgentId() + "'";
//            }
            db.rs = db.st.executeQuery(sqlQuery);
            if (db.rs.next()) {
                if (db.rs.getInt("status") != 0) {
                  setVisible(false);
                    JOptionPane.showMessageDialog(rootPane, "Card already issue");
                     
                     return;
                }
                id = db.rs.getInt("id");
                var.setPixPath(db.rs.getString("pix"));
                getpicture(var.getPixPath());
                jButton1.setEnabled(true);
                jLabel6.setText("VIN: " + db.rs.getString("reg_id"));
                jLabel4.setText("PU: " + db.rs.getString("placeofreg"));
                jLabel3.setText("DATE OF ISSUE: " + db.rs.getString("colectiondate"));
                jLabel12.setText(db.rs.getString("firstname").toUpperCase() + ", " + db.rs.getString("secondname").toUpperCase() + " " + db.rs.getString("othername").toUpperCase());
                jLabel20.setText(db.rs.getString("dob"));
                long now = System.currentTimeMillis(); // Simpler way to get current time
                Date date3 = new Date();
                String date = new SimpleDateFormat("yyyy").format(date3.getTime());
                Date d = new Date(db.rs.getString("dob"));
                String date2 = new SimpleDateFormat("yyyy").format(d.getTime());
                int thisdate = Integer.parseInt(date);
                int yy = Integer.parseInt(date2);
                int yr = (thisdate) - (yy - 1);
                System.out.println("yr : " + yr + " thiisday : " + thisdate + " yy :" + yy);
                jLabel22.setText(yr + "");
                jLabel10.setText(db.rs.getString("occupation"));
                jLabel13.setText(db.rs.getString("gender"));
                jLabel18.setText(db.rs.getString("street"));
                jButton1.setEnabled(true);

                return;

            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid Info Supply");
                setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "There was a Problem retrying this data");
            e.printStackTrace();
        }

    }

    private void getpicture(String path) {
        try {
            File eff = new File(path);
            BufferedImage image = ImageIO.read(eff);
            Image mee = image.getScaledInstance(90, 100, BufferedImage.SCALE_SMOOTH);


            jLabel24.setIcon(new ImageIcon(mee)); // NOI18N
            this.repaint();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("picture " + e);
        }
    }

    void log(String event) {
        Date d = new Date();
        try {
            db.ps = db.con.prepareStatement("INSERT INTO `voters_reg`.`log` (`transactiontype` ,`agentid` ,`systemid` ,`date` ,`status`)VALUES (?,?,?,?,?) ");
            db.ps.setString(1, event);
            db.ps.setString(2, var.getUsername());
            db.ps.setString(3, "");//system id goes here
            SimpleDateFormat dateTime = new SimpleDateFormat("HH:mm:ss dd-MMM-yyyy");
            db.ps.setString(4, dateTime.format(d.getTime()));
            db.ps.setString(5, "0");
            db.ps.executeUpdate();
        } catch (Exception e) {
            //    JOptionPane.showMessageDialog("", e);
        }

    }
}
