package voters_admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author damhiesax
 */
public class Updatesys extends javax.swing.JFrame {

    DbConnect dbcon = new DbConnect();
    ResultSetMetaData md;
    String firstname, lastname, PassWord, address, mobileNo, administrator, username, Userid;
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    Statement st;
    Vector<String> data = new Vector<String>();
    Variables var;
    String sysid = "";
    public static String[] rowData;
    JOptionPane jp;
int id;
int status;
    /**
     * Creates new form UserReg
     */
    public Updatesys() {
        initComponents();
        setTitle("Staff Registration Page");
        var = new Variables();
        jp =new JOptionPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Registraion");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("System Brand:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 150, 80, 14);

        jLabel3.setText("Remark:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 270, 50, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 50, 200, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 230, 220, 30);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton1.setText("Update");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 390, 100, 27);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 390, 100, 27);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Update System");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 4, 130, 20);

        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 0, 350, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 270, 220, 100);

        jLabel5.setText("System Maker:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 80, 14);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 110, 220, 30);

        jLabel6.setText("Serial No:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 230, 70, 14);

        jLabel8.setText("System ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 60, 70, 14);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(120, 150, 220, 30);

        jCheckBox1.setText("Disable");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(40, 350, 70, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 92, 350, 10);

        jButton4.setText("GO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(300, 53, 50, 30);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(229, 225, 225));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(120, 190, 220, 30);

        jLabel2.setText("New Systen ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 190, 80, 14);

        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 40, 350, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addnew();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
     
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
if(!jTextField3.getText().isEmpty() && !jTextField4.getText().isEmpty()){
     checkForPresence();
     jTextField5.setText(sysid);
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
      if(!jTextField3.getText().isEmpty() && !jTextField4.getText().isEmpty()){
     checkForPresence();
     jTextField5.setText(sysid);
     }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        userLogin();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatesys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updatesys().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

   void userLogin() {
        if (jTextField1.getText().isEmpty()) {
            jp.showMessageDialog(rootPane, "System ID require", "System Update", jp.ERROR_MESSAGE);
            jTextField1.requestFocus();
            return;
        }

        //testing if internet connection is available

        try {
            String sqlQuery = "select *  from system where systemid='" + jTextField1.getText() + "'";
            dbcon.rs = dbcon.st.executeQuery(sqlQuery);
            if (dbcon.rs.next()) {
                jCheckBox1.setEnabled(true);
                jButton1.setEnabled(true);
                status = dbcon.rs.getInt("status");
                if (status != 0) {
                    jCheckBox1.setText("Enable");
                }
                id = dbcon.rs.getInt("id");
                jTextField4.setText(dbcon.rs.getString("maker"));
                jTextField5.setText(dbcon.rs.getString("systemid"));
                jTextField3.setText(dbcon.rs.getString("name"));
                jTextField2.setText(dbcon.rs.getString("serial_no"));
                jTextArea1.setText(dbcon.rs.getString("systemdetails"));
                this.repaint();
                return;

            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid Info Supply");
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "There was a Problem retrying this data");
            e.printStackTrace();
        }

    }

    void addnew() {
        String emt = "";
        if (jTextField5.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "System ID  not set");
            return;
        }
        if (jTextArea1.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "At least a word");
            return;
        }
        if (jTextField2.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "System serial no required");
            return;
        }
        if (jTextField3.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Supply system maker");
            return;
        }
        if (jTextField4.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Supply the system brand");
            return;
        }
       

        try {
            dbcon.ps = dbcon.con.prepareStatement("Update system SET systemid=?,serial_no=?,name=?,maker=?,systemdetails=?,status=? where id="+id);
            dbcon.ps.setString(1, jTextField5.getText());
            dbcon.ps.setString(2, jTextField2.getText());
            dbcon.ps.setString(3, jTextField3.getText());
            dbcon.ps.setString(4, jTextField4.getText());
            dbcon.ps.setString(5, jTextArea1.getText());
            if (jCheckBox1.getText().equalsIgnoreCase("Enable") && jCheckBox1.isSelected()) {
                status=0;
            } else if (jCheckBox1.getText().equalsIgnoreCase("Disable") && jCheckBox1.isSelected()) {
 
                status= 1;
            } 
            dbcon.ps.setInt(6, status);
            dbcon.ps.executeUpdate();
             log("System Alter");
            JOptionPane.showMessageDialog(rootPane, "System Updated successfully..");
           
              this.dispose();
        } catch (Exception g) {
            System.out.println("System not Update successfully.." + g);
        }
    }

    boolean checkForPresence() {
        int id = (int) (Math.random() * 9999);
        String newId = id + "";
        if (newId.length() == 1) {
            newId = "000" + newId;
        } else if (newId.length() == 2) {
            newId = "00" + newId;
        } else if (newId.length() == 3) {
            newId = "0" + newId;
        }
        String mak="",brd="";
        if(jTextField3.getText().length()>3){
        mak=jTextField3.getText().substring(0,3);
        }else{
          mak=jTextField3.getText();
        }
        if(jTextField4.getText().length()>3){
          brd=jTextField4.getText().substring(0,3);
        }else{
          brd=jTextField4.getText();
        }
       boolean present = false;
       sysid=mak+"/"+brd+"/"+newId;
       sysid=sysid.toUpperCase();
        try {
            dbcon.rs = dbcon.st.executeQuery("select * from system where systemid='" + sysid + "'");
            if (dbcon.rs.next()) {
                present = true;
            }
        } catch (Exception g) {
            System.out.println("" + g);
        }
        return present;
    }
    void log(String event){
           try {
               Date d=new Date();
                dbcon.ps=dbcon.con.prepareStatement("INSERT INTO `voters_reg`.`log` (`transactiontype` ,`agentid` ,`systemid` ,`date` ,`status`)VALUES (?,?,?,?,?) ");
             dbcon.ps.setString(1, event);
            dbcon.ps.setString(2, var.getUsername());
            dbcon.ps.setString(3, "");//system id goes here
             SimpleDateFormat dateTime = new SimpleDateFormat("HH:mm:ss dd-MMM-yyyy");
            dbcon.ps.setString(4, dateTime.format(d.getTime()));
            dbcon.ps.setString(5, "0");
            dbcon.ps.executeUpdate();
           } catch (Exception e) {
              // e.printStackTrace();
           }  
      }
}
